name: publish-to-aur

on:
  push:
    branch:
      - "main"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "$ID_RSA" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Check if SSH key is stored
        run: ssh-keyscan github.com


