name: publish-to-aur

on:
  push:
    branch:
      - "main"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: aur
          known_hosts: ${{ secrets.KNOWN_HOST }}
          if_key_exists: fail
        run: |
          ssk-keyscan aur.archlinux.org
          

