name: publish-to-aur

on:
  push:
    branch:
      - "main"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this fine duck
        uses: actions/checkout@v3

      - name: Load ssh-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: aur
          known_hosts: ${{ secrets.KNOWN_HOST }}
          if_key_exists: fail
      
      - name: verify ssh-key
        run: |
          ssh-keyscan aur.archlinux.org
          

