name: publish-to-aur

on:
  push:
    branch:
      - "main"

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: play with it now
        run: |
          echo "Hello World"
          echo $ID_RSA
